/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "GTM_ATOM_3_Phase_Inverter_PWM.h"
#include "DRV8313_handle.h"
#include "Bsp.h"

#define WAIT_TIME_MS    (10U)

#ifndef BSP_SIMPLEFOC_OPEN_LOOP_TEST
#define BSP_SIMPLEFOC_OPEN_LOOP_TEST (0)
#endif

#ifndef BSP_SIMPLEFOC_OPEN_LOOP_BUS_V
#define BSP_SIMPLEFOC_OPEN_LOOP_BUS_V (24.0f)
#endif

#ifndef BSP_SIMPLEFOC_OPEN_LOOP_VOLTAGE_LIMIT_V
#define BSP_SIMPLEFOC_OPEN_LOOP_VOLTAGE_LIMIT_V (2.0f)
#endif

#ifndef BSP_SIMPLEFOC_OPEN_LOOP_TARGET_RAD_S
#define BSP_SIMPLEFOC_OPEN_LOOP_TARGET_RAD_S (5.0f)
#endif

#if BSP_SIMPLEFOC_OPEN_LOOP_TEST
#include "simplefoc_tc375_port.hpp"
#endif

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

void core0_main(void)
{
    Ifx_TickTime ticksFor10ms;

    IfxCpu_enableInterrupts();

    /*
     * Disable CPU and Safety Watchdogs.
     */
    IfxScuWdt_disableCpuWatchdog(
        IfxScuWdt_getCpuWatchdogPassword()
    );

    IfxScuWdt_disableSafetyWatchdog(
        IfxScuWdt_getSafetyWatchdogPassword()
    );

    /*
     * Wait for CPU synchronization.
     */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    /*
     * Initialize delay time.
     */
    ticksFor10ms = IfxStm_getTicksFromMilliseconds(
        BSP_DEFAULT_TIMER,
        WAIT_TIME_MS
    );

#if BSP_SIMPLEFOC_OPEN_LOOP_TEST
    if (SimpleFocTc375_OpenLoopInit(
            BSP_SIMPLEFOC_OPEN_LOOP_BUS_V,
            BSP_SIMPLEFOC_OPEN_LOOP_VOLTAGE_LIMIT_V) == false)
    {
        Drv8313_disable();

        while (1)
        {
            waitTime(ticksFor10ms);
        }
    }
#else
    /*
     * Initialize DRV8313 GPIO pins.
     *
     * After this function:
     * nRT = low
     * nSP = low
     * Driver is disabled.
     */
    Drv8313_init();

    /*
     * Initialize GTM ATOM PWM.
     *
     * Make sure the initial duty cycles are zero
     * or another safe value inside this function.
     */
    initGtmAtom3phInv();

    /*
     * Enable DRV8313 after PWM initialization.
     *
     * nSP goes high first, then nRT goes high.
     */
    Drv8313_enable();
#endif

    while (1)
    {
        /*
         * nFT is active low.
         */
        if (Drv8313_hasFault() == TRUE)
        {
            /*
             * Stop updating PWM and disable the driver.
             */
#if BSP_SIMPLEFOC_OPEN_LOOP_TEST
            SimpleFocTc375_OpenLoopStop();
#else
            GtmAtom3phInv_setSafeDuty();
#endif
            Drv8313_disable();

            /*
             * Stay here after a fault.
             * A system reset is required to restart.
             */
            while (1)
            {
                waitTime(ticksFor10ms);
            }
        }
        else
        {
            /*
             * Update the three-phase PWM duty cycles.
             */
#if BSP_SIMPLEFOC_OPEN_LOOP_TEST
            SimpleFocTc375_OpenLoopStep(BSP_SIMPLEFOC_OPEN_LOOP_TARGET_RAD_S);
#else
            GtmAtom3phInv_setSafeDuty();
#endif
        }

        waitTime(ticksFor10ms);
    }
}
