/**********************************************************************************************************************
 * \file GTM_ATOM_3_Phase_Inverter_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_ATOM_3_Phase_Inverter_PWM.h"
#include "Ifx_Types.h"
#include "IfxGtm_Pwm.h"
#include "IfxPort.h"
#include "IfxPort_Pinmap.h"
#include "project_config.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NUM_OF_CHANNELS         (3)                                    /* Number of DRV8313 PWM input channels       */
#define PWM_FREQUENCY           ((float32)MOTOR_PWM_FREQUENCY_HZ)      /* PWM frequency in [Hz]                      */

#define PHASE_U_HS              &IfxGtm_ATOM1_0_TOUT9_P00_0_OUT         /* Phase U PWM: P00.0 */
#define PHASE_V_HS              &IfxGtm_ATOM1_1_TOUT11_P00_2_OUT        /* Phase V PWM: P00.2 */
#define PHASE_W_HS              &IfxGtm_ATOM1_2_TOUT12_P00_3_OUT        /* Phase W PWM: P00.3 */

#define PHASE_U_DUTY            (0.0f)                                /* Initial PWM duty cycle of phase U in [%]   */
#define PHASE_V_DUTY            (0.0f)                                /* Initial PWM duty cycle of phase V in [%]   */
#define PHASE_W_DUTY            (0.0f)                                /* Initial PWM duty cycle of phase W in [%]   */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
        IfxGtm_Pwm          pwm;                                /* PWM Driver handle                                 */
        IfxGtm_Pwm_Channel  channels[NUM_OF_CHANNELS];          /* Array containing channel data after configuration */
        float32             dutyCycles[NUM_OF_CHANNELS];        /* Duty Cycle values to hold                         */
        float32             phases[NUM_OF_CHANNELS];            /* PhaseShift values to hold                         */
} GtmAtom3phInv;

IFX_STATIC GtmAtom3phInv g_gtmAtom3phInv;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
static float32 GtmAtom3phInv_clampDuty(float32 duty)
{
    if (duty < GTM_ATOM_3PH_INV_DUTY_MIN_PERCENT)
    {
        return GTM_ATOM_3PH_INV_DUTY_MIN_PERCENT;
    }

    if (duty > GTM_ATOM_3PH_INV_DUTY_MAX_PERCENT)
    {
        return GTM_ATOM_3PH_INV_DUTY_MAX_PERCENT;
    }

    return duty;
}

/* This function initializes the ATOM */
void initGtmAtom3phInv(void)
{
    /* Configuration variables
     * Neither application (in most of the cases) nor the PWM driver need configuration variables post initialization.
     * It is recommended to define such variables within the function (local), alternatively such structures could
     * also be initialized (element-wise) as constant (in FLASH)
     */
    IfxGtm_Pwm_Config config;                                /* Main PWM configuration structure                     */
    IfxGtm_Pwm_ChannelConfig channelConfig[NUM_OF_CHANNELS]; /* Array containing configuration for each channel      */
    IfxGtm_Pwm_OutputConfig output[NUM_OF_CHANNELS];         /* Only needed if connected to pin                      */

    /* 1. Configuration structure initialization
     * If the configuration structure is located in the RAM, the initConfig API would be handy to initialize the
     * elements to their default values
     */
    IfxGtm_Pwm_initConfig(&config, &MODULE_GTM);

    /* 2. Output configuration
     * Output configurations are optional.
     */

    /* DRV8313 uses one PWM input per phase. Low-side complementary drive is generated by the gate driver. */

    /* CH0 configurations */
    output[0].pin                   = (IfxGtm_Pwm_ToutMap*)PHASE_U_HS;          /* Phase U PWM input / high-side     */
    output[0].complementaryPin      = NULL_PTR;                                 /* DRV8313 handles complementary LS  */
    output[0].polarity              = Ifx_ActiveState_high;                     /* Active low/high of pin            */
    output[0].complementaryPolarity = Ifx_ActiveState_low;                      /* Active low/high of pin            */
    output[0].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                       */
    output[0].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                        */

    /* CH1 configurations */
    output[1].pin                   = (IfxGtm_Pwm_ToutMap*)PHASE_V_HS;          /* Phase V PWM input / high-side     */
    output[1].complementaryPin      = NULL_PTR;                                 /* DRV8313 handles complementary LS  */
    output[1].polarity              = Ifx_ActiveState_high;                     /* Active low/high of pin            */
    output[1].complementaryPolarity = Ifx_ActiveState_low;                      /* Active low/high of pin            */
    output[1].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                       */
    output[1].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                        */

    /* CH2 configurations */
    output[2].pin                   = (IfxGtm_Pwm_ToutMap*)PHASE_W_HS;          /* Phase W PWM input / high-side     */
    output[2].complementaryPin      = NULL_PTR;                                 /* DRV8313 handles complementary LS  */
    output[2].polarity              = Ifx_ActiveState_high;                     /* Active low/high of pin            */
    output[2].complementaryPolarity = Ifx_ActiveState_low;                      /* Active low/high of pin            */
    output[2].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                       */
    output[2].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                        */

    /* 3. Channel configuration */
    /*Base channel - CH0 configuration. */
    channelConfig[0].timerCh      = IfxGtm_Pwm_SubModule_Ch_0;   /* Atom channel index to be used for sync channel   */
    channelConfig[0].phase        = 0.0f;                        /* Phase shift in radians (range: 0.0 .. 2pi;
                                                                  * only for edge aligned sync channels)             */
    channelConfig[0].duty         = PHASE_U_DUTY;                /* PWM duty in % (range: 0.0 .. 100.0)              */
    channelConfig[0].dtm          = NULL_PTR;                    /* DRV8313 owns complementary low-side timing       */
    channelConfig[0].output       = &output[0];                  /* Pin connections and polarities for this channel  */
    channelConfig[0].mscOut       = NULL_PTR;                    /* MSC configuration for this channel               */
    channelConfig[0].interrupt    = NULL_PTR;                    /* PWM generation needs no periodic CPU interrupt   */

    /* Sync channel - CH1 configuration */
    channelConfig[1].timerCh      = IfxGtm_Pwm_SubModule_Ch_1;   /* Atom channel index to be used for base channel   */
    channelConfig[1].phase        = 0.0f;                        /* Phase shift in radians (range: 0.0 .. 2pi;
                                                                  * only for edge aligned sync channels)             */
    channelConfig[1].duty         = PHASE_V_DUTY;                /* PWM duty in % (range: 0.0 .. 100.0)              */
    channelConfig[1].dtm          = NULL_PTR;                    /* DRV8313 owns complementary low-side timing       */
    channelConfig[1].output       = &output[1];                  /* Pin connections and polarities for this channel  */
    channelConfig[1].mscOut       = NULL_PTR;                    /* MSC configuration for this channel               */
    channelConfig[1].interrupt    = NULL_PTR;                    /* Interrupt configuration for this channel         */

    /*Sync channel CH2 configuration.*/
    channelConfig[2].timerCh      = IfxGtm_Pwm_SubModule_Ch_2;   /* Atom channel index to be used for sync channel   */
    channelConfig[2].phase        = 0.0f;                        /* Phase shift in radians (range: 0.0 .. 2pi;
                                                                  * only for edge aligned sync channels)             */
    channelConfig[2].duty         = PHASE_W_DUTY;                /* PWM duty in % (range: 0.0 .. 100.0)              */
    channelConfig[2].dtm          = NULL_PTR;                    /* DRV8313 owns complementary low-side timing       */
    channelConfig[2].output       = &output[2];                  /* Pin connections and polarities for this channel  */
    channelConfig[2].mscOut       = NULL_PTR;                    /* MSC configuration for this channel               */
    channelConfig[2].interrupt    = NULL_PTR;                    /* Interrupt configuration for this channel         */

    /* 4. Other configurations */
    config.cluster                = IfxGtm_Cluster_1;                  /* Cluster                                    */
    config.subModule              = IfxGtm_Pwm_SubModule_atom;         /* Sub module                                 */
    config.alignment              = IfxGtm_Pwm_Alignment_center;       /* Alignment                                  */
    config.syncStart              = TRUE;                              /* Start all channels after init              */
    config.numChannels            = NUM_OF_CHANNELS;                   /* Number of channels configured              */
    config.channels               = channelConfig;                     /* Attach Channel configuration               */
    config.frequency              = PWM_FREQUENCY;                     /* PWM frequency                              */
    config.clockSource.atom       = IfxGtm_Cmu_Clk_0;                  /* Clock source for atom                      */
    config.dtmClockSource         = IfxGtm_Dtm_ClockSource_cmuClock0;  /* Clock source for dtm                       */
    config.syncUpdateEnabled      = TRUE;                              /* TRUE: Update compare registers from shadow
                                                                        * at the end of period */

    /* 5. Call the init function */

    if(!IfxGtm_isEnabled(&MODULE_GTM))
    {
        float32 frequency;
        /* Enable GTM, it is necessary if the GTM is not initialized earlier */
        IfxGtm_enable(&MODULE_GTM);

        frequency = IfxGtm_Cmu_getModuleFrequency(&MODULE_GTM);
        /* Set the global clock frequency to the max */
        IfxGtm_Cmu_setGclkFrequency(&MODULE_GTM, frequency);
        /* Set the CMU CLK0 */
        IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, frequency);
        /* Enable the FXU clock */
        IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);
    }

    IfxGtm_Pwm_init(&g_gtmAtom3phInv.pwm, &g_gtmAtom3phInv.channels[0], &config);

    /* 6. Store the current duty values for runtime calls */
    g_gtmAtom3phInv.dutyCycles[0]= channelConfig[0].duty;
    g_gtmAtom3phInv.dutyCycles[1]= channelConfig[1].duty;
    g_gtmAtom3phInv.dutyCycles[2]= channelConfig[2].duty;
}

/* This function update duty cycles */
void GtmAtom3phInv_setDuty(float dutyU,
                           float dutyV,
                           float dutyW)
{
    g_gtmAtom3phInv.dutyCycles[0] = GtmAtom3phInv_clampDuty(dutyU);
    g_gtmAtom3phInv.dutyCycles[1] = GtmAtom3phInv_clampDuty(dutyV);
    g_gtmAtom3phInv.dutyCycles[2] = GtmAtom3phInv_clampDuty(dutyW);

    /* Immediate update is kept for open-loop bring-up only. Use synchronized shadow update for closed-loop FOC. */
    IfxGtm_Pwm_updateChannelsDutyImmediate(
        &g_gtmAtom3phInv.pwm,
        g_gtmAtom3phInv.dutyCycles);
}

void GtmAtom3phInv_setSafeDuty(void)
{
    GtmAtom3phInv_setDuty(0.0f, 0.0f, 0.0f);
}
