################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Configurations/Debug \
Configurations \
. \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Infra/Ssw/TC3xx/Tricore \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/Service/CpuGeneric/SysSe/General \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/Service/CpuGeneric/SysSe/Time \
Libraries/iLLD/TC3xx/Tricore/Asclin/Asc \
Libraries/iLLD/TC3xx/Tricore/Asclin/Lin \
Libraries/iLLD/TC3xx/Tricore/Asclin/Spi \
Libraries/iLLD/TC3xx/Tricore/Asclin/Std \
Libraries/iLLD/TC3xx/Tricore/Can/Can \
Libraries/iLLD/TC3xx/Tricore/Can/Std \
Libraries/iLLD/TC3xx/Tricore/Ccu6/Icu \
Libraries/iLLD/TC3xx/Tricore/Ccu6/PwmBc \
Libraries/iLLD/TC3xx/Tricore/Ccu6/PwmHl \
Libraries/iLLD/TC3xx/Tricore/Ccu6/Std \
Libraries/iLLD/TC3xx/Tricore/Ccu6/TPwm \
Libraries/iLLD/TC3xx/Tricore/Ccu6/Timer \
Libraries/iLLD/TC3xx/Tricore/Ccu6/TimerWithTrigger \
Libraries/iLLD/TC3xx/Tricore/Cif/Cam \
Libraries/iLLD/TC3xx/Tricore/Cif/Std \
Libraries/iLLD/TC3xx/Tricore/Convctrl/Std \
Libraries/iLLD/TC3xx/Tricore/Cpu/Irq \
Libraries/iLLD/TC3xx/Tricore/Cpu/Std \
Libraries/iLLD/TC3xx/Tricore/Cpu/Trap \
Libraries/iLLD/TC3xx/Tricore/Dma/Dma \
Libraries/iLLD/TC3xx/Tricore/Dma/Std \
Libraries/iLLD/TC3xx/Tricore/Dts/Dts \
Libraries/iLLD/TC3xx/Tricore/Dts/Std \
Libraries/iLLD/TC3xx/Tricore/Ebu/BFlashSpansion \
Libraries/iLLD/TC3xx/Tricore/Ebu/BFlashSt \
Libraries/iLLD/TC3xx/Tricore/Ebu/Dram \
Libraries/iLLD/TC3xx/Tricore/Ebu/Sram \
Libraries/iLLD/TC3xx/Tricore/Ebu/Std \
Libraries/iLLD/TC3xx/Tricore/Edsadc/Edsadc \
Libraries/iLLD/TC3xx/Tricore/Edsadc/Std \
Libraries/iLLD/TC3xx/Tricore/Emem/Std \
Libraries/iLLD/TC3xx/Tricore/Eray/Eray \
Libraries/iLLD/TC3xx/Tricore/Eray/Std \
Libraries/iLLD/TC3xx/Tricore/Evadc/Adc \
Libraries/iLLD/TC3xx/Tricore/Evadc/Std \
Libraries/iLLD/TC3xx/Tricore/Fce/Crc \
Libraries/iLLD/TC3xx/Tricore/Fce/Std \
Libraries/iLLD/TC3xx/Tricore/Flash/Std \
Libraries/iLLD/TC3xx/Tricore/Geth/Eth \
Libraries/iLLD/TC3xx/Tricore/Geth/Std \
Libraries/iLLD/TC3xx/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC3xx/Tricore/Gpt12/Std \
Libraries/iLLD/TC3xx/Tricore/Gtm/Atom/Dtm_PwmHl \
Libraries/iLLD/TC3xx/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC3xx/Tricore/Gtm/Atom/PwmHl \
Libraries/iLLD/TC3xx/Tricore/Gtm/Atom/Timer \
Libraries/iLLD/TC3xx/Tricore/Gtm/Pwm \
Libraries/iLLD/TC3xx/Tricore/Gtm/Std \
Libraries/iLLD/TC3xx/Tricore/Gtm/Tim/In \
Libraries/iLLD/TC3xx/Tricore/Gtm/Tim/Timer \
Libraries/iLLD/TC3xx/Tricore/Gtm/Tom/Dtm_PwmHl \
Libraries/iLLD/TC3xx/Tricore/Gtm/Tom/Pwm \
Libraries/iLLD/TC3xx/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC3xx/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC3xx/Tricore/Gtm/Trig \
Libraries/iLLD/TC3xx/Tricore/Hspdm/Std \
Libraries/iLLD/TC3xx/Tricore/Hssl/Hssl \
Libraries/iLLD/TC3xx/Tricore/Hssl/Std \
Libraries/iLLD/TC3xx/Tricore/I2c/I2c \
Libraries/iLLD/TC3xx/Tricore/I2c/Std \
Libraries/iLLD/TC3xx/Tricore/Iom/Driver \
Libraries/iLLD/TC3xx/Tricore/Iom/Iom \
Libraries/iLLD/TC3xx/Tricore/Iom/Std \
Libraries/iLLD/TC3xx/Tricore/Msc/Msc \
Libraries/iLLD/TC3xx/Tricore/Msc/Std \
Libraries/iLLD/TC3xx/Tricore/Mtu/Std \
Libraries/iLLD/TC3xx/Tricore/Pms/Std \
Libraries/iLLD/TC3xx/Tricore/Port/Io \
Libraries/iLLD/TC3xx/Tricore/Port/Std \
Libraries/iLLD/TC3xx/Tricore/Psi5/Psi5 \
Libraries/iLLD/TC3xx/Tricore/Psi5/Std \
Libraries/iLLD/TC3xx/Tricore/Psi5s/Psi5s \
Libraries/iLLD/TC3xx/Tricore/Psi5s/Std \
Libraries/iLLD/TC3xx/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC3xx/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC3xx/Tricore/Qspi/Std \
Libraries/iLLD/TC3xx/Tricore/Rif/Rif \
Libraries/iLLD/TC3xx/Tricore/Rif/Std \
Libraries/iLLD/TC3xx/Tricore/Scu/Std \
Libraries/iLLD/TC3xx/Tricore/Sdmmc/Emmc \
Libraries/iLLD/TC3xx/Tricore/Sdmmc/Sd \
Libraries/iLLD/TC3xx/Tricore/Sdmmc/Std \
Libraries/iLLD/TC3xx/Tricore/Sent/Sent \
Libraries/iLLD/TC3xx/Tricore/Sent/Std \
Libraries/iLLD/TC3xx/Tricore/Smu/Smu \
Libraries/iLLD/TC3xx/Tricore/Smu/Std \
Libraries/iLLD/TC3xx/Tricore/Spu/Std \
Libraries/iLLD/TC3xx/Tricore/Src/Std \
Libraries/iLLD/TC3xx/Tricore/Stm/Std \
Libraries/iLLD/TC3xx/Tricore/Stm/Timer \
Libraries/iLLD/TC3xx/Tricore/_Impl \
Libraries/iLLD/TC3xx/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC3xx/Tricore/_Lib/InternalMux \
Libraries/iLLD/TC3xx/Tricore/_PinMap/TC37x \

